version: "2"
services:

  web:
    # build: .
    image: ctftraining/pwnhub_2017_open_weekday
    ports:
      - "127.0.0.1:8081:80"
    # volumes:
    #   - /data/challenge/logs:/var/log/nginx
    restart: always
    environment:
      - FLAG=flag{test_flag}
